package com.teethcare.common;

public enum Message {
    SUCCESS_FUNCTION,
    INVALID_STATUS,
    PARAMS_MISSING,
    DATE_ERROR,
    UPDATE_FAIL,
    DENTIST_NO_AVAILABLE,
    NO_COMMIT_FROM_DENTIST,
    ERROR_SENDMAIL,
    ERROR_SEND_NOTIFICATION
}
