package com.teethcare.common;

public enum Message {
    //OK
    SUCCESS_FUNCTION,
    //BAD_REQUEST
    INVALID_STATUS,
    //BAD_REQUEST
    PARAMS_MISSING,
    //BAD_REQUEST
    DATE_ERROR,
    //BAD_REQUEST
    UPDATE_FAIL,
    //BAD_REQUEST
    DENTIST_NO_AVAILABLE,
    //BAD_REQUEST
    NO_COMMIT_FROM_DENTIST,
    //INTERNAL_SERVER_ERROR
    ERROR_SENDMAIL,
    //INTERNAL_SERVER_ERROR
    ERROR_SEND_NOTIFICATION,
    //BAD_REQUEST
    OUT_OF_WORKING_TIME,
    //BAD_REQUEST
    CREATE_FAIL,
    WORKING_TIME_INVALID
    CREATE_FAIL,
    NOT_FOUND,
    WRONG_STATUS,
    UNABLE_TO_CHECKIN,
    NOT_REACH_TIME_CHECKIN
}
