package com.teethcare.common;

import javax.annotation.Resource;

public enum NotificationType {
    NORMAL_NOTIFICATION,
    OPEN_BOOKING_NOTIFICATION,
    UPDATE_BOOKING_1ST_NOTIFICATION,
    UPDATE_BOOKING_2RD_NOTIFICATION,
    CONFIRM_BOOKING_SUCCESS,
    CONFIRM_BOOKING_FAIL,
    CHECK_IN_SUCCESS,
    CHECK_OUT_SUCCESS,
    CREATE_APPOINTMENT_SUCCESS,
    CREATE_APPOINTMENT_FAIL
}
